version: "3.8"

services:
  servis1:
    image: servis1:1.0
    ports:
      - "8001:8000"
    networks:
      - servisna_mreza

  servis2:
    image: servis2:1.0
    ports:
      - "8002:8000"
    networks:
      - servisna_mreza

  servis3:
    image: servis3:1.0
    ports:
      - "8003:8000"
    networks:
      - servisna_mreza

networks:
  servisna_mreza:
    driver: bridge
